# list in python

In [3]:
# enumerate: (index, element)
mylist = ['a', 'b','c']
for i, element in enumerate(mylist):
    print("{} is {}st element".format(element, i+1))

a is 1st element
b is 2st element
c is 3st element


In [4]:
# dict: items; tuple-shpaed

In [8]:
list1 = [1,2,3]
list3 = list1   # 같은 object생성 
list3 is list1

[1, 2, 3]

In [9]:
list1[2] = 4
list3

In [15]:
# initialize: property input으로 제시
class Creature():
    def __init__(self, name, weight):
        self.name = name
        self.weight = weight
    def eat(self, weight):
        weight += 1

In [16]:
lion = Creature("lion","100")

In [17]:
(1 == 1) & (2==2)

True

In [18]:
1 == 1&2

False

In [20]:
student_dict = {"a":1, "b":2,"c":3}
list(zip(student_dict.keys(),student_dict.values()))

[('a', 1), ('b', 2), ('c', 3)]

## Numpy

In [26]:
import numpy as np

In [24]:
np.__version__

'1.14.0'

In [27]:
np.array([1.0,2.0], dtype = 'float32')   # 32bit를 사용하는 이유가 있음!

array([1., 2.], dtype=float32)

In [28]:
np.zeros(10, dtype = "float32")

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [31]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [32]:
np.ones((3,3), dtype = 'float32')

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [34]:
np.full((3,3), 500)   # single number

array([[500, 500, 500],
       [500, 500, 500],
       [500, 500, 500]])

In [39]:
np.random.random((3,3))   # (0,1) uniform dist.

array([[0.53939143, 0.45876457, 0.80693721],
       [0.27615675, 0.93895221, 0.56918863],
       [0.15022708, 0.98651425, 0.19120975]])

In [44]:
np.random.normal(0,1,[3,3])   # (mean, sd(scale))

array([[ 1.40020826,  1.16603714,  0.39148638],
       [-1.06243799, -0.80203218, -1.93045896],
       [-0.24361618,  0.31955355, -0.85468358]])

In [45]:
np.eye(3)   # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.empty(10)   # 초기값은 random하게 공간 확보

array([1.72723371e-077, 1.72723371e-077, 2.47032823e-323, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 6.95335581e-309])

In [50]:
np.random.seed(593)
x1 = np.random.randint(10, size = (2,2,2))
x1

array([[[7, 0],
        [8, 2]],

       [[2, 0],
        [1, 4]]])

In [54]:
x1.shape
np.shape(x1)   # numpy라는 class이용, x1이라는 객체, shape이라는 함수

(2, 2, 2)

In [55]:
x1.size

8

In [58]:
x2 = np.random.randint(10, size = (3,3))
x2

array([[8, 1, 6],
       [4, 6, 8],
       [5, 0, 8]])

In [65]:
x2[1]

array([4, 6, 8])

In [60]:
x2[1,]

array([4, 6, 8])

In [62]:
x2[1,:]

array([4, 6, 8])

In [63]:
x2[1:2, :]   # make matrix 

array([[4, 6, 8]])

In [66]:
x2[:2, :2]

array([[8, 1],
       [4, 6]])

In [67]:
x3 = x2.copy()   # 객체 자체가 동일해지는 것이 아니라, 내용물만 copy

In [68]:
x3

array([[8, 1, 6],
       [4, 6, 8],
       [5, 0, 8]])

In [75]:
x4 = x3[1]
x4.reshape((1,3))

array([[4, 6, 8]])

In [78]:
x4.reshape(3)

array([4, 6, 8])

In [79]:
x4[np.newaxis, :]

array([[4, 6, 8]])

In [93]:
x = np.arange(0,3)
y = np.arange(4,7)
xy = np.concatenate([x,y])
xy

array([0, 1, 2, 4, 5, 6])

In [95]:
xmat = x.reshape(1,3)
ymat = y.reshape(1,3)
np.concatenate([x,y])

array([0, 1, 2, 4, 5, 6])

In [98]:
xymat = np.concatenate([x,y], axis = 1)  # axis = 1; col 방향으로 연결
xymat

array([0, 1, 2, 4, 5, 6])

In [106]:
np.vstack([xmat, ymat])   # row 방향으로 추가


array([[0, 1, 2],
       [4, 5, 6]])

In [101]:
np.hstack([xmat, ymat])  # col 방향으로 추가

array([[0, 1, 2, 4, 5, 6]])

In [102]:
xmat + 4  # np.add(x, 4)

array([[4, 5, 6]])

In [104]:
np.linspace(0,100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [173]:
xx = np.array([1,1])
yy = np.array([2,1])
xx,yy
np.concatenate([xx,yy], axis = 0)

array([1, 1, 2, 1])

In [116]:
rand_x = np.random.random((3,3))
rand_x

array([[0.06887895, 0.21665968, 0.31448711],
       [0.05273948, 0.66753346, 0.52577622],
       [0.41998208, 0.99766663, 0.78608851]])

In [118]:
np.add.reduce(rand_x, axis = 0)   # col 방향으로 더함

array([0.5416005 , 1.88185977, 1.62635184])

In [120]:
np.add.reduce(rand_x, axis = 1)   # row 방향으로 더함, reduce가 뭐지...?

array([0.60002574, 1.24604916, 2.20373721])

In [119]:
np.sum(rand_x, axis = 1)

array([0.60002574, 1.24604916, 2.20373721])

In [121]:
import pandas as pd

In [122]:
data = pd.read_csv("president_heights.csv")

In [127]:
data.head()

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183

In [128]:
height = np.array(data["height(cm)"])

In [129]:
height

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 168, 170, 178, 182, 180,
       183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188,
       188, 182, 185])

In [136]:
data.describe()["height(cm)"]

count     42.000000
mean     179.738095
std        7.015869
min      163.000000
25%      174.250000
50%      182.000000
75%      183.000000
max      193.000000
Name: height(cm), dtype: float64

In [134]:
data["name"][np.argmax(height)]

'Abraham Lincoln'

In [135]:
data["name"][np.argmin(height)]

'James Madison'

In [139]:
data["height(cm)"].quantile(0.9)

188.0

In [143]:
data.name[data["height(cm)"] == 188.0]

29    Franklin D. Roosevelt
38        George H. W. Bush
39             Bill Clinton
Name: name, dtype: object

## broadcasting

In [156]:
a = np.array([0,1,2]).reshape(3,1)
a.shape
a

array([[0],
       [1],
       [2]])

In [157]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [158]:
a+M

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [167]:
M2 = np.array([100,200,300]).reshape(1,3)

In [163]:
M2

array([[100],
       [200],
       [300]])

In [168]:
a+M2

array([[100, 200, 300],
       [101, 201, 301],
       [102, 202, 302]])