# Pandas 

## 1. Series

In [2]:
# Pandas의 Series는 value랑 index를 반환한다. 
# 이는 Numpy array와 유사하다. 
import pandas as pd
import numpy as np
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)
print(data.values)
print(data.index)
print(data[1]) # array와 마찬가지로 indexing을 할 수 있다. 

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
[0.25 0.5  0.75 1.  ]
RangeIndex(start=0, stop=4, step=1)
0.5


In [8]:
# string을 index로 사용할 수 있다. 
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
print(data)
print(data['b']) # string인 index를 사용해 slicing 할 수 있다. 

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.5


In [7]:
# Pandas Series를 dict로 간주(keys-values)
population_dict = {'California': 223123, 'Texas': 342342, 'New york': 456464, 'Florida': 234490, 'Illinois': 9848723}
population = pd.Series(population_dict)
print(population)
# Series에서 자동으로 key들을 index로 만들기에 dict처럼 접근할 수 있다. 
print(population['Texas'])
# Series에서는 dict 에서 할 수 없는 slicing 을 할 수 있다. 
population['California':'Florida']

California     223123
Texas          342342
New york       456464
Florida        234490
Illinois      9848723
dtype: int64
342342


California    223123
Texas         342342
New york      456464
Florida       234490
dtype: int64

## 2. DataFrame

### a. Definition of DataFrame in Pandas

In [15]:
# Series가 index들이 있는 1차원 array라고 본다면, Dataframe 은 행과 열의 index가 있는 2차원 array라고 볼 수 있다. 
area_dict = {'California': 12345, 'Texas': 56789, 'New york': 11111, 'Florida': 99999, 'Illinois': 33333}
area = pd.Series(area_dict)
print(area)
# 이제 위의 population Series와 결합해보자. 
states = pd.DataFrame({'population': population,
                      'area': area})
print(states)
# 이는 두 Series가 공통된 index를 가지고 있기에 가능. 

California    12345
Texas         56789
New york      11111
Florida       99999
Illinois      33333
dtype: int64
            population   area
California      223123  12345
Texas           342342  56789
New york        456464  11111
Florida         234490  99999
Illinois       9848723  33333


### b. Constructing DataFrames

In [36]:
# pd.DataFrame(data=, index=, columns=, dtype=, copy= )

# Single column Dataframe by single series
print(pd.DataFrame(population, columns = ['population']))

# List of Dicts 
data = [{'a':i, 'b': 2 * i} for i in range(3)]
print(pd.DataFrame(data))

# Missing keys -> NAN
print(pd.DataFrame([{'a':1, 'b':2}, {'b':3, 'c':4}]))

# 2-dim. Numpy array
pd.DataFrame(np.random.rand(3,2), columns = ['foo', 'bar'], 
            index = ['a', 'b', 'c'])

# Numpy structured array
A = np.zeros(3, dtype = [('A', 'i8'), ('B', 'f8')]) # i8: 8byte integer, f8: 8byte float
A
pd.DataFrame(A)


            population
California      223123
Texas           342342
New york        456464
Florida         234490
Illinois       9848723
   a  b
0  0  0
1  1  2
2  2  4
     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0


A    B
0  0  0.0
1  0  0.0
2  0  0.0

### c. Indexing the DataFrame

In [47]:
# Index = Immutable array
ind = pd.Index([2,3,5,7,8])
ind
print(ind[1])
print(ind[::3]) # 3개씩 건너서 뽑아달라. 
print(ind.size, ind.shape, ind.ndim, ind.dtype)
# numpy array와 비슷하지만 다른 점은 수정이 안된다. 

3
Int64Index([2, 7], dtype='int64')
5 (5,) 1 int64


In [51]:
# Index = Ordered Set(순서집합)
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])
print(indA & indB) # 교집합
print(indA | indB) # 합집합
print(indA ^ indB) # 대칭차(합-교)

Int64Index([3, 5, 7], dtype='int64')
Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')
Int64Index([1, 2, 9, 11], dtype='int64')


In [62]:
# Data Indexing 
data= pd.Series([0.25, 0.5, 0.75, 1.0], 
               index = ['a', 'b', 'c', 'd'])
print(data)
print(data['b'])

# 특정 index/value의 존재여부
'a' in data
data.keys()
list(data.items()) # 리스트로 만들어 볼 수 있다. 


a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.5


a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [69]:
# Modification 

data['e']= 1.25
print(data)
data['b'] = 1000
print(data)

a       0.25
b    1000.00
c       0.75
d       1.00
e       1.25
dtype: float64
a       0.25
b    1000.00
c       0.75
d       1.00
e       1.25
dtype: float64
a       0.25
b    1000.00
c       0.75
dtype: float64
a       0.25
b    1000.00
dtype: float64


In [76]:
# Slicing 

print(data['a':'c'])
# data[['a', 'e']] : 연속적이지 않은 index 한꺼번에 가져오기. 
print(data[0:2]) # index의 숫자로도 slicing 가능

# Masking 
data[(data > 0.3) * (data < 0.8)]

a       0.25
b    1000.00
c       0.75
dtype: float64
a       0.25
b    1000.00
dtype: float64


C:\Users\Kyungbin Park\Documents\Python Scripts\lib\site-packages\pandas\core\computation\expressions.py:180: UserWarning: evaluating in Python space because the '*' operator is not supported by numexpr for the bool dtype, use '&' instead
  .format(op=op_str, alt_op=unsupported[op_str]))


c    0.75
dtype: float64

In [92]:
# Indexers : loc, iloc
# 가끔 index가 integer로 되어있을 때 index의 해당숫자를 말하는 것인지, 위치를 말하는 것인지 헷갈림

# Loc : explicit index
print(data)
data.loc[1] # index가 1인 value가 없기에 error
data.loc[1:3]

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [1] of <class 'int'>

In [95]:
# Iloc : Implicit index(위치)

print(data)
print(data.iloc[1])
print(data.iloc[1:3])
print(data.loc['a'])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.5
b    0.50
c    0.75
dtype: float64
0.25


### 4. Data Selection in Dataframe

In [102]:
# Dataframe as a dict
# Dataframe을 같은 index를 가지는 Series의 dict로 생각할 수 있다. 
print(area)
print(population)
data = pd.DataFrame({'area': area, 'population': population})
data

California    12345
Texas         56789
New york      11111
Florida       99999
Illinois      33333
dtype: int64
California     223123
Texas          342342
New york       456464
Florida        234490
Illinois      9848723
dtype: int64


area  population
California  12345      223123
Texas       56789      342342
New york    11111      456464
Florida     99999      234490
Illinois    33333     9848723

In [105]:
# 따라서 Dict과 같이 접근할 수 있다. 
print(data['area'])
print(data.area)
# 하지만 만약 column name이 string이 아닐경우, dataFrame의 method와 겹칠 경우 안될 때도 있다. 

California    12345
Texas         56789
New york      11111
Florida       99999
Illinois      33333
Name: area, dtype: int64
California    12345
Texas         56789
New york      11111
Florida       99999
Illinois      33333
Name: area, dtype: int64


In [108]:
# Add a new column
data['density'] = data['population'] / data['area']
data

area  population     density
California  12345      223123   18.073957
Texas       56789      342342    6.028315
New york    11111      456464   41.082171
Florida     99999      234490    2.344923
Illinois    33333     9848723  295.464645

In [125]:
# dict 처럼 value에 접근
print(data.values)
print(data.values[0]) # Array index로 접근하면 row를 가져온다. 
print(data['area'])   # Dataframe에 index로 접근하면 행을 가져온다. 


[[1.23450000e+04 2.23123000e+05 1.80739571e+01]
 [5.67890000e+04 3.42342000e+05 6.02831534e+00]
 [1.11110000e+04 4.56464000e+05 4.10821708e+01]
 [9.99990000e+04 2.34490000e+05 2.34492345e+00]
 [3.33330000e+04 9.84872300e+06 2.95464645e+02]]
[1.23450000e+04 2.23123000e+05 1.80739571e+01]
California    12345
Texas         56789
New york      11111
Florida       99999
Illinois      33333
Name: area, dtype: int64
               California          Texas       New york        Florida  \
area         12345.000000   56789.000000   11111.000000   99999.000000   
population  223123.000000  342342.000000  456464.000000  234490.000000   
density         18.073957       6.028315      41.082171       2.344923   

                Illinois  
area        3.333300e+04  
population  9.848723e+06  
density     2.954646e+02  


In [126]:
# Transpose
print(data.T)

               California          Texas       New york        Florida  \
area         12345.000000   56789.000000   11111.000000   99999.000000   
population  223123.000000  342342.000000  456464.000000  234490.000000   
density         18.073957       6.028315      41.082171       2.344923   

                Illinois  
area        3.333300e+04  
population  9.848723e+06  
density     2.954646e+02  


In [130]:
# iloc / loc으로 array같은 indexing
print(data.iloc[:3, :2])
print(data.loc[:'Illinois', :'population'])

             area  population
California  12345      223123
Texas       56789      342342
New york    11111      456464
             area  population
California  12345      223123
Texas       56789      342342
New york    11111      456464
Florida     99999      234490
Illinois    33333     9848723


In [134]:
# ix indexer : hybrid of iloc and loc
print(data.ix[:3, :'population'])

# etc: masking + fancy indexing
data.loc[data.density > 100, ['pop', 'density']]

             area  population
California  12345      223123
Texas       56789      342342
New york    11111      456464


C:\Users\Kyungbin Park\Documents\Python Scripts\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  
C:\Users\Kyungbin Park\Documents\Python Scripts\lib\site-packages\pandas\core\indexing.py:1472: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


pop     density
Illinois  NaN  295.464645

In [141]:
data.iloc[0,2] = 90 # modification

# Slicing 은 행의 slicing 을 의미한다. 
print(data['Florida':'Illinois'])
print(data[1:3])
print(data[data.density > 100])

           area  population     density
Florida   99999      234490    2.344923
Illinois  33333     9848723  295.464645
           area  population    density
Texas     56789      342342   6.028315
New york  11111      456464  41.082171
           area  population     density
Illinois  33333     9848723  295.464645


In [3]:
# 모든 Index가 채워지지 않은 경우
A = pd.Series([2,4,6], index = [0,1,2])
B = pd.Series([1,3,5], index = [1,2,3])
A+B
# NaN 은 좋지 않다. 따라서 채워넣는다. 

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [4]:
A.add(B, fill_value = 0) 

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [9]:
# Index를 Dataframe에서 편하게 만들기 
A = pd.DataFrame(np.random.randint(0,20, (2,2)), 
                columns = list('AB'))
print(A)
B = pd.DataFrame(np.random.randint(0,10,(3,3)), 
                columns = list('BAC'))
print(B)

    A   B
0  19  17
1  19   4
   B  A  C
0  5  5  3
1  0  3  1
2  7  1  9


In [12]:
print(A+B) # 더하면 NaN이 생성된다. 
# A의 빈부분을 A의 평균으로 채워보자 
fill = A.stack().mean()
A.add(B, fill_value = fill)

      A     B   C
0  24.0  22.0 NaN
1  22.0   4.0 NaN
2   NaN   NaN NaN


A      B      C
0  24.00  22.00  17.75
1  22.00   4.00  15.75
2  15.75  21.75  23.75

In [25]:
# default indexing 은 row -> column으로 변경하기
A = np.random.randint(10, size = (3,4))
df = pd.DataFrame(A, columns = list('QRST'))
print(df - df.iloc[0])
# column 기준 : axis = 0
df.subtract(df['R'], axis = 0)

   Q  R  S  T
0  0  0  0  0
1  1 -1 -2  2
2 -2  5  0  2


Q  R  S  T
0  3  0  5  4
1  5  0  4  7
2 -4  0  0  1

## Missing Values

In [29]:
# NA 확인하기 
data = pd.Series([1, np.nan, 'hello', None])
print(data.isnull()) # NA인가 T/F
data[data.notnull()] # NA 아닌 값 반환

0    False
1     True
2    False
3     True
dtype: bool


0        1
2    hello
dtype: object

In [34]:
# NA 지우기
data.dropna()
# DataFrame 에서 NA처리
df = pd.DataFrame([[1, np.nan, 2], 
                 [2, 3, 5], 
                 [np.nan, 4, 6]])
# df.dropna() : NA가 있는 모든 행 제거
df.dropna()
# df.dropna(axis = 1 or axis = 'columns') : NA가 있는 모든 열 제거
df.dropna(axis = 1)

2
0  2
1  5
2  6

In [39]:
# NA 채우기
data = pd.Series([1,np.nan, 2, None, 3], index = list('abcde'))
print(data)
data.fillna(0)

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64


a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [41]:
# 바로 앞에 있는 값으로 채우기
print(data.fillna(method = 'ffill'))

# 바로 뒤의 값으로 채우기
print(data.fillna(method = 'bfill'))

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64
a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64


## Hierarchical Indexing :
### incorporating multiple index levels within a single index

In [51]:
# Pandas multi-index
# 1차원 Series 안에 2차원의 data를 어떻게 구현할 것인가?

index = [('Cali', 2000), ('Cali', 2010), 
        ('NY', 2000), ('NY', 2010), 
        ('Texas', 2000), ('Texas', 2010)]
populations = [34234234, 2342342, 43543435, 23424342, 56757657, 234244]
pop = pd.Series(populations, index = index)
pop 
# 데이터 추출하기 불편하다. 

(Cali, 2000)     34234234
(Cali, 2010)      2342342
(NY, 2000)       43543435
(NY, 2010)       23424342
(Texas, 2000)    56757657
(Texas, 2010)      234244
dtype: int64

In [52]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['Cali', 'NY', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [57]:
pop = pop.reindex(index)
pop

Cali   2000    34234234
       2010     2342342
NY     2000    43543435
       2010    23424342
Texas  2000    56757657
       2010      234244
dtype: int64

In [61]:
# slicing by pandas slicing 
print(pop[:, 2010])
# unstack the multiindex
pop_df = pop.unstack()
pop_df

Cali      2342342
NY       23424342
Texas      234244
dtype: int64


2000      2010
Cali   34234234   2342342
NY     43543435  23424342
Texas  56757657    234244

In [65]:
pop['Cali', 2000]

34234234

In [67]:
# Rearranging Multi-indices

index = pd.MultiIndex.from_product([['a','c','b'], [1,2]])
data = pd.Series(np.random.rand(6), index = index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.927370
      2      0.520305
c     1      0.669524
      2      0.007868
b     1      0.605911
      2      0.630556
dtype: float64

In [72]:
# data['a':'b'] : Error
# 에러의 이유는 Sorted 되지 않아서. 
data = data.sort_index()
data

char  int
a     1      0.927370
      2      0.520305
b     1      0.605911
      2      0.630556
c     1      0.669524
      2      0.007868
dtype: float64

In [73]:
data['a':'b']

char  int
a     1      0.927370
      2      0.520305
b     1      0.605911
      2      0.630556
dtype: float64

In [77]:
# stack된 multi-index dataset을 2차원으로 변환하기
pop
print(pop.unstack(level = 0)) # state 기준 
print(pop.unstack(level = 1)) # 년도 기준

          Cali        NY     Texas
2000  34234234  43543435  56757657
2010   2342342  23424342    234244
           2000      2010
Cali   34234234   2342342
NY     43543435  23424342
Texas  56757657    234244


In [79]:
# 원래대로 unstacking
pop.unstack().stack()

Cali   2000    34234234
       2010     2342342
NY     2000    43543435
       2010    23424342
Texas  2000    56757657
       2010      234244
dtype: int64